export const runtime = 'edge'

export const metadata = {
  title: 'Privacy Policy - CosmetCheck',
  description: 'CosmetCheck Privacy Policy covering GDPR, LGPD, and LFPDPPP compliance',
}

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container-custom max-w-3xl py-20">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
        <p className="text-gray-500 mb-12">Last updated: May 12, 2025</p>

        <div className="prose prose-gray max-w-none">
          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              CosmetCheck (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, store, and protect your personal data when you use our cosmetic compliance checking service.
            </p>
            <p className="text-gray-600 leading-relaxed">
              We comply with the General Data Protection Regulation (GDPR) for users in the European Union, the Lei Geral de Proteção de Dados (LGPD) for users in Brazil, and the Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) for users in Mexico.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Data We Collect</h2>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">2.1 Product Information</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              We collect product information that you voluntarily submit for compliance checking, including:
            </p>
            <ul className="list-disc list-inside text-gray-600 mb-4 space-y-1">
              <li>Product names and descriptions</li>
              <li>Ingredient lists</li>
              <li>Target markets (e.g., Brazil, Mexico)</li>
            </ul>

            <h3 className="text-lg font-semibold text-gray-800 mb-2">2.2 Account Information</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              When you create an account, we collect:
            </p>
            <ul className="list-disc list-inside text-gray-600 mb-4 space-y-1">
              <li>Email address</li>
              <li>Name (optional)</li>
              <li>Subscription tier and usage data</li>
            </ul>

            <h3 className="text-lg font-semibold text-gray-800 mb-2">2.3 Technical Data</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              We automatically collect certain technical information, including IP addresses, browser type, and device information, for security and analytics purposes.
            </p>

            <h3 className="text-lg font-semibold text-gray-800 mb-2">2.4 AI-Generated Content</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              When you use our AI Listing generation feature, the product information you provide 
              (name, ingredients, benefits) is sent to our AI service provider (DeepSeek) for processing.
            </p>
            <ul className="list-disc list-inside text-gray-600 mb-4 space-y-1">
              <li><strong>No Training:</strong> DeepSeek does NOT use your input data to train their AI models. Your product information is processed only for the purpose of generating your listing.</li>
              <li><strong>Processing Only:</strong> Data is sent to DeepSeek&apos;s API for inference only and is not retained for model training purposes by DeepSeek.</li>
              <li><strong>Output Ownership:</strong> AI outputs are generated by us based on your input. You retain full ownership of both your input and the generated content.</li>
              <li>AI-generated content may be used for your commercial purposes, but you bear compliance responsibility</li>
              <li><strong>Data Minimization:</strong> We send only the minimum product information necessary to generate compliant listings.</li>
            </ul>

            <h3 className="text-lg font-semibold text-gray-800 mb-2">2.5 Payment Data</h3>
            <p className="text-gray-600 leading-relaxed">
              Payment information is processed by Stripe. We do not store complete credit card numbers. 
              Stripe handles your payment data according to their privacy policy.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. How We Use Your Data</h2>
            <p className="text-gray-600 leading-relaxed mb-4">We use your data to:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1">
              <li>Provide cosmetic compliance checking services</li>
              <li>Generate AI-powered listings in Portuguese and Spanish</li>
              <li>Process payments and manage subscriptions</li>
              <li>Improve our regulatory database and detection accuracy</li>
              <li>Communicate service updates and regulatory changes</li>
              <li>Prevent fraud and abuse</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Lawful Basis for Processing</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              We process your personal data based on the following lawful bases, depending on your jurisdiction:
            </p>
            <div className="overflow-x-auto mb-4">
              <table className="min-w-full border border-gray-200 text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">Processing Activity</th>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">GDPR (EU)</th>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">LGPD (Brazil)</th>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">LFPDPPP (Mexico)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="px-4 py-2 border-b">Account registration</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 6(1)(a))</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 11)</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 8)</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Compliance checking</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 6(1)(f))</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 10)</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 17)</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">AI Listing generation</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 6(1)(a))</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 11)</td>
                    <td className="px-4 py-2 border-b">Consent (Art. 8)</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Payment processing</td>
                    <td className="px-4 py-2 border-b">Contract Performance (Art. 6(1)(b))</td>
                    <td className="px-4 py-2 border-b">Contract Performance (Art. 7)</td>
                    <td className="px-4 py-2 border-b">Contract Performance (Art. 17)</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Analytics & security</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 6(1)(f))</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 10)</td>
                    <td className="px-4 py-2 border-b">Legitimate Interest (Art. 17)</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2">Marketing communications</td>
                    <td className="px-4 py-2">Consent (Art. 6(1)(a))</td>
                    <td className="px-4 py-2">Consent (Art. 11)</td>
                    <td className="px-4 py-2">Consent (Art. 8)</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-gray-600 leading-relaxed">
              You have the right to withdraw consent at any time. Withdrawal does not affect the lawfulness of processing based on consent before its withdrawal.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Data Storage and Security</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              All data is transmitted using TLS encryption and stored in secure, SOC 2-compliant data centers. We use Supabase for database hosting with Row Level Security (RLS) enabled.
            </p>
            <p className="text-gray-600 leading-relaxed">
              We do not sell your data to third parties. Product information is used solely for compliance checking purposes.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Your Rights</h2>
            <p className="text-gray-600 leading-relaxed mb-4">Under GDPR, LGPD, and LFPDPPP, you have the right to:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1">
              <li><strong>Access your personal data</strong> — Request a copy of all data we hold about you</li>
              <li><strong>Correct inaccurate data</strong> — Request correction of incorrect or incomplete data</li>
              <li><strong>Delete your data</strong> (right to erasure) — Request permanent deletion of your personal data</li>
              <li><strong>Export your data</strong> (data portability) — Download your data in JSON or CSV format</li>
              <li><strong>Withdraw consent</strong> at any time for processing based on consent</li>
              <li><strong>Object to data processing</strong> — Opt out of specific processing activities</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              <strong>How to Export Your Data:</strong> Navigate to <strong>Account Settings → Privacy → Export My Data</strong>. 
              Your data export will be generated and emailed to your registered address within <strong>72 hours</strong>. 
              Alternatively, email <strong>privacy@cosmetcheck.com</strong> with subject &quot;Data Export Request&quot;.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Data Retention</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              We retain your personal data only for as long as necessary to fulfill the purposes outlined in this policy. The specific retention periods are:
            </p>
            <div className="overflow-x-auto mb-4">
              <table className="min-w-full border border-gray-200 text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">Data Category</th>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">Retention Period</th>
                    <th className="px-4 py-2 text-left font-semibold text-gray-900 border-b">Deletion Method</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="px-4 py-2 border-b">Account data (email, name)</td>
                    <td className="px-4 py-2 border-b">Until account deletion + 30 days</td>
                    <td className="px-4 py-2 border-b">Automated deletion</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Product compliance data</td>
                    <td className="px-4 py-2 border-b">Until account deletion + 90 days</td>
                    <td className="px-4 py-2 border-b">Automated deletion</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">AI-generated content</td>
                    <td className="px-4 py-2 border-b">Until account deletion (on-demand)</td>
                    <td className="px-4 py-2 border-b">User-requested deletion</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Payment & billing records</td>
                    <td className="px-4 py-2 border-b">7 years (legal requirement)</td>
                    <td className="px-4 py-2 border-b">Secure archival</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Analytics & logs</td>
                    <td className="px-4 py-2 border-b">12 months</td>
                    <td className="px-4 py-2 border-b">Automated rotation</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 border-b">Session & authentication tokens</td>
                    <td className="px-4 py-2 border-b">30 days of inactivity</td>
                    <td className="px-4 py-2 border-b">Automated expiration</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2">Marketing consent records</td>
                    <td className="px-4 py-2">Until consent withdrawal</td>
                    <td className="px-4 py-2">User-requested deletion</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-gray-600 leading-relaxed mb-4">
              <strong>Account Deletion:</strong> You can delete your account at any time via Account Settings → Privacy → Delete Account, or by emailing privacy@cosmetcheck.com. 
              We will process deletion requests within <strong>30 days</strong>.
            </p>
            <p className="text-gray-600 leading-relaxed">
              After account deletion, certain data may be retained for legal compliance (e.g., tax records for 7 years under Brazilian law).
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Contact Us</h2>
            <p className="text-gray-600 leading-relaxed">
              For privacy-related questions or to exercise your rights, please contact us at:
            </p>
            <p className="text-gray-600 leading-relaxed mt-2">
              Email: privacy@cosmetcheck.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
