export const metadata = {
  title: 'Disclaimer - CosmetCheck',
  description: 'CosmetCheck Disclaimer - AI Content & Compliance Advisory',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container-custom max-w-3xl py-20">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Disclaimer</h1>
        <p className="text-gray-500 mb-12">Last updated: May 2025</p>

        <div className="prose prose-gray max-w-none">
          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. General Disclaimer</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              CosmetCheck provides automated compliance checking and AI-generated content 
              for informational purposes only. The service does not constitute legal advice, 
              and we are not a law firm or legal consultancy.
            </p>
            <p className="text-gray-600 leading-relaxed">
              <strong>You should always verify compliance requirements with qualified professionals 
              familiar with your specific products and target markets.</strong>
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. AI-Generated Content</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our AI-generated product listings (titles, descriptions, bullet points) are 
              generated by machine learning models based on the information you provide. 
              They are provided as starting points for your own content, not as final, 
              ready-to-use copy.
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-2">
              <li>We do not guarantee the accuracy, completeness, or fitness for any purpose</li>
              <li>AI outputs may contain errors, omissions, or outdated information</li>
              <li>Regulatory requirements change frequently; AI may not reflect the latest rules</li>
              <li>You are responsible for reviewing and verifying all AI-generated content</li>
              <li>We recommend human review before publishing any AI-generated content</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Compliance Information</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our compliance detection tool checks against known regulations (ANVISA, COFEPRIS) 
              based on our database. However:
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-2">
              <li>Regulations change frequently; our database may not be up-to-date</li>
              <li>We cannot detect every possible regulatory requirement</li>
              <li>Your specific product formulation may have unique compliance needs</li>
              <li>Local authorities may interpret regulations differently than our tool</li>
              <li>New products or ingredients may not be in our database</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. No Guarantee of Outcomes</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              We do not guarantee:
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-2">
              <li>That your products will pass customs or regulatory inspection</li>
              <li>That AI-generated listings will convert or sell</li>
              <li>That compliance checks will detect all potential issues</li>
              <li>That our service will be uninterrupted or error-free</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              To the maximum extent permitted by law, CosmetCheck shall not be liable for:
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-2">
              <li>Fines, penalties, or legal fees resulting from non-compliance</li>
              <li>Product recalls or market withdrawals</li>
              <li>Financial losses from customs seizure or product rejection</li>
              <li>Reputation damage from non-compliant listings</li>
              <li>Any indirect, incidental, or consequential damages</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Professional Advice</h2>
            <p className="text-gray-600 leading-relaxed mb-4">
              For significant business decisions, we strongly recommend consulting:
            </p>
            <ul className="list-disc list-inside text-gray-600 space-y-2">
              <li>A qualified attorney specializing in cosmetic regulations</li>
              <li>A regulatory consultant with expertise in your target market</li>
              <li>Your company&apos;s legal or compliance department</li>
              <li>Official regulatory agency resources (ANVISA, COFEPRIS)</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Updates to This Disclaimer</h2>
            <p className="text-gray-600 leading-relaxed">
              We may update this disclaimer at any time. Continued use of our service 
              constitutes acceptance of this disclaimer.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              For questions about this disclaimer: support@cosmetcheck.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}